theme: jekyll-theme-minimal

title: the Blog
description: You can read censored posts from selected Wechat public accounts. Thanks to JMSC at The University of Hong Kong for their amazing tool Wechatscope (http://wechatscope.jmsc.hku.hk/).

# Build settings
plugins:
  - jekyll-feeds

author: Michael
