theme: jekyll-theme-minimal

# name of the site
name: the Blog

# short bio or discription
discription: Welcome to THE Blog on the Internet.

# form my github profile pic
avatar: https://avatars2.githubusercontent.com/u/16777746?s=400&u=2c63a5b8d200f6dc76dd2ed54353dcf7f9945f01&v=4

# update file if time is from futre
future: true
