theme: jekyll-theme-minimal

title: the Blog
email: michael.liu916@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Welcome to THE Blog on the Internet.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
plugins:
  - jekyll-feeds

# form my github profile pic
avatar: https://avatars2.githubusercontent.com/u/16777746?s=400&u=2c63a5b8d200f6dc76dd2ed54353dcf7f9945f01&v=4
